FROM ubuntu:16.04
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT Release

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    curl \
    && rm -rf /var/lib/apt/lists/*
RUN echo deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main > /etc/apt/sources.list.d/dotnetdev.list
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg
RUN apt-get update && apt-get install -y \
    dotnet-sdk-2.0.3 \
    && rm -rf /var/lib/apt/lists/*
